"""Add chunk table and body col

Revision ID: 10877e2cf996
Revises: 4738a29e567f
Create Date: 2026-08-21 22:08:45.209450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10877e2cf996'
down_revision: Union[str, Sequence[str], None] = '4738a29e567f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails_indexed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_email_id'), 'chunks', ['email_id'], unique=False)
    op.create_index(op.f('ix_chunks_gmail_message_id'), 'chunks', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_chunks_gmail_thread_id'), 'chunks', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_chunks_sender'), 'chunks', ['sender'], unique=False)
    op.create_index(op.f('ix_chunks_sent_at'), 'chunks', ['sent_at'], unique=False)
    op.add_column('emails_indexed', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails_indexed', 'body')
    op.drop_index(op.f('ix_chunks_sent_at'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_sender'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_gmail_thread_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_gmail_message_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_email_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
