"""Add ColdEmailDraft

Revision ID: 143d8fa3e362
Revises: 98fcd3ca2d10
Create Date: 2026-08-23 15:43:01.614944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '143d8fa3e362'
down_revision: Union[str, Sequence[str], None] = '98fcd3ca2d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cold_email_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_context', sa.Text(), nullable=False),
    sa.Column('original_body', sa.Text(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cold_email_drafts_id'), 'cold_email_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_cold_email_drafts_user_id'), 'cold_email_drafts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cold_email_drafts_user_id'), table_name='cold_email_drafts')
    op.drop_index(op.f('ix_cold_email_drafts_id'), table_name='cold_email_drafts')
    op.drop_table('cold_email_drafts')
    # ### end Alembic commands ###
