"""Add status to emails_indexed

Revision ID: 4738a29e567f
Revises: ad594521b9a2
Create Date: 2026-08-21 21:30:55.057085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4738a29e567f'
down_revision: Union[str, Sequence[str], None] = 'ad594521b9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails_indexed', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails_indexed', 'status')
    # ### end Alembic commands ###
