"""Add EmailSendLog

Revision ID: 98fcd3ca2d10
Revises: c3ffc11079e6
Create Date: 2026-08-23 15:00:02.369232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fcd3ca2d10'
down_revision: Union[str, Sequence[str], None] = 'c3ffc11079e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_sends_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('draft_reference', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_sends_log_id'), 'email_sends_log', ['id'], unique=False)
    op.create_index(op.f('ix_email_sends_log_user_id'), 'email_sends_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_sends_log_user_id'), table_name='email_sends_log')
    op.drop_index(op.f('ix_email_sends_log_id'), table_name='email_sends_log')
    op.drop_table('email_sends_log')
    # ### end Alembic commands ###
