"""init tables

Revision ID: ad594521b9a2
Revises: 
Create Date: 2026-08-19 05:51:53.102095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad594521b9a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('expected_answer_notes', sa.Text(), nullable=True),
    sa.Column('baseline_answer', sa.Text(), nullable=True),
    sa.Column('agent_answer', sa.Text(), nullable=True),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('agent_score', sa.Float(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_question_id'), 'eval_results', ['question_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmail_access_token', sa.LargeBinary(), nullable=True),
    sa.Column('gmail_refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('gmail_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_connected', sa.Boolean(), nullable=False),
    sa.Column('gmail_send_scope_granted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('emails_indexed',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chroma_chunk_ids', sa.Text(), nullable=True),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_indexed_gmail_message_id'), 'emails_indexed', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_emails_indexed_gmail_thread_id'), 'emails_indexed', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_emails_indexed_sender'), 'emails_indexed', ['sender'], unique=False)
    op.create_index(op.f('ix_emails_indexed_sent_at'), 'emails_indexed', ['sent_at'], unique=False)
    op.create_index(op.f('ix_emails_indexed_user_id'), 'emails_indexed', ['user_id'], unique=False)
    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_facts_user_id'), 'memory_facts', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('career_info', sa.Text(), nullable=True),
    sa.Column('writing_style_samples', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_index(op.f('ix_memory_facts_user_id'), table_name='memory_facts')
    op.drop_table('memory_facts')
    op.drop_index(op.f('ix_emails_indexed_user_id'), table_name='emails_indexed')
    op.drop_index(op.f('ix_emails_indexed_sent_at'), table_name='emails_indexed')
    op.drop_index(op.f('ix_emails_indexed_sender'), table_name='emails_indexed')
    op.drop_index(op.f('ix_emails_indexed_gmail_thread_id'), table_name='emails_indexed')
    op.drop_index(op.f('ix_emails_indexed_gmail_message_id'), table_name='emails_indexed')
    op.drop_table('emails_indexed')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_eval_results_question_id'), table_name='eval_results')
    op.drop_table('eval_results')
    # ### end Alembic commands ###
