"""update memory_facts schema

Revision ID: c3ffc11079e6
Revises: 589a812cf888
Create Date: 2026-08-23 09:12:00.049275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ffc11079e6'
down_revision: Union[str, Sequence[str], None] = '589a812cf888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_facts', sa.Column('fact_type', sa.String(length=50), nullable=True))
    op.add_column('memory_facts', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('memory_facts', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('memory_facts', 'provider')
    op.drop_column('memory_facts', 'source_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_facts', sa.Column('source_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('memory_facts', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('memory_facts', 'active')
    op.drop_column('memory_facts', 'source')
    op.drop_column('memory_facts', 'fact_type')
    # ### end Alembic commands ###
